### ISSUE TITLE
高等数学一 考试页面异常报错

### ISSUE THREAD

**Issue by Rushyoung** [ginnnnnncc/GinsMooc#11]
感谢大佬的付出！
课程id：NEU-1001639002
控制台输出：
![image](https://github.com/ginnnnnncc/GinsMooc/assets/74442033/deb320d4-b57c-4eff-9461-f4b6f93dd483)
链接：https://www.icourse163.org/learn/NEU-1001639002?tid=xxx#/learn/examlist
显示：
![image](https://github.com/ginnnnnncc/GinsMooc/assets/74442033/a4d28d1f-e653-4f02-952c-9db16e405912)
这个页面还要再进一层页面才有quiz id
似乎在不应该报错的地方报错了（

**Comment by ginnnnnncc** [comment]
预期行为，有时候会有多个考试

**Comment by Rushyoung** [comment]
报错信息会不断生成，滚动条在蹦迪
![image](https://github.com/ginnnnnncc/GinsMooc/assets/74442033/c4a883a4-1d0a-4c00-a0e6-a6ce198a4f96)
还有想请教一下大佬题库是怎么个获取法，这场考试的题库没对上，准备就绪后进入考试，获取答案的按钮也没显示出来😂

**Comment by ginnnnnncc** [comment]
把别的插件关掉试试

**Comment by Rushyoung** [comment]
> 把别的插件关掉试试

考完就出来了😂
PS.去大佬您的网站上的题库翻了一下，发现网站上的题库里没有我这场的题目－O－

**Comment by ginnnnnncc** [comment]
> > 把别的插件关掉试试
> 
> 考完就出来了😂 PS.去大佬您的网站上的题库翻了一下，发现网站上的题库里没有我这场的题目－O－

看看你啥题，我刚试完满分

**Comment by ginnnnnncc** [comment]
提示添加课程失败，后端出了点问题，在检查

**Comment by ginnnnnncc** [comment]
现在应该好了

**Comment by Rushyoung** [comment]
非常感谢q(≧▽≦q)
