### ISSUE TITLE
突然不好用了

### ISSUE THREAD

**Issue by dannis2005** [ginnnnnncc/GinsMooc#12]
感谢大佬付出，浏览器插件突然显示不了答案了，获取答案一直失败，打开网页版也是空白的。
![360截图20240318145123896](https://github.com/ginnnnnncc/GinsMooc/assets/163821055/05545b24-6079-49dd-9fb7-a1163b404cef)
![360截图20240318145201589](https://github.com/ginnnnnncc/GinsMooc/assets/163821055/584c9d88-3396-4ef2-85a7-0454b775a3cc)

**Comment by ginnnnnncc** [comment]
数据库挂了，现在好了

**Comment by dannis2005** [comment]
我有一个课一直正在获取答案就是获取不出来，课程代码1472046444

**Comment by ginnnnnncc** [comment]
可能有bug，今晚我看一下
&nbsp;


gin
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月18日(星期一) 下午3:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [ginnnnnncc/GinsMooc] 突然不好用了 (Issue #12)





 
我有一个课一直正在获取答案就是获取不出来，课程代码1472046444

**Comment by dannis2005** [comment]
> 可能有bug，今晚我看一下 &nbsp; gin ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年3月18日(星期一) 下午3:12 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; "State ***@***.***&gt;; 主题: Re: [ginnnnnncc/GinsMooc] 突然不好用了 (Issue #12) 我有一个课一直正在获取答案就是获取不出来，课程代码1472046444 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

好的感谢

**Comment by ginnnnnncc** [comment]
线代可以看到题目了
