### ISSUE TITLE
页面显示大叉

### ISSUE THREAD

**Issue by dannis2005** [ginnnnnncc/GinsMooc#13]
大佬您好，最近插件总是在页面最下面显示这个巨大的叉，想看看能不能解决下，谢谢
![image](https://github.com/ginnnnnncc/GinsMooc/assets/163821055/6c2eb965-00e9-4377-9dfd-8c26f7578d49)

**Comment by ginnnnnncc** [comment]
你是哪个课程，我刚试了线代的，没有啊。你的是最新的吗

**Comment by dannis2005** [comment]
我刚才看了一下，他内个好像是随机出现的，有的时候有有的时候没有

**Comment by iris2881** [comment]
大佬，我是最新的，刚刚试了太极功夫和其他几个课程，都出不了答案，下面也是大叉，麻烦大佬看看是什么情况呢

**Comment by ginnnnnncc** [comment]
> 大佬，我是最新的，刚刚试了太极功夫和其他几个课程，都出不了答案，下面也是大叉，麻烦大佬看看是什么情况呢

我这边试了下可以正常用，应该是网络问题，下次遇到转[网页](https://ginnnnnn.top/mooc/)对着查先吧，等我有空改一下插件吧

**Comment by ginnnnnncc** [comment]
以后不会再有大叉了
