### ISSUE TITLE
长时间加载不出来

### ISSUE THREAD

**Issue by bargehaulersonvolga** [ginnnnnncc/GinsMooc#14]
![moocbug](https://github.com/ginnnnnncc/GinsMooc/assets/170289560/89cbdcd2-9f3d-4b5b-9972-63a85c5eae8e)
![moocbug](https://github.com/ginnnnnncc/GinsMooc/assets/170289560/d96cf329-bf5f-4a88-9b88-2b042d03fa6f)

**Comment by bargehaulersonvolga** [comment]
![image](https://github.com/ginnnnnncc/GinsMooc/assets/170289560/b910d0d7-48f1-4271-b685-df7e00e77b62)
在测试外面也是长时间没有反应

**Comment by bargehaulersonvolga** [comment]
![image](https://github.com/ginnnnnncc/GinsMooc/assets/170289560/fc4be936-e3aa-4194-a117-6d436e30bfe0)
点进去以后往下滑会这样子

**Comment by ginnnnnncc** [comment]
哪个课程，给下课程id

**Comment by moonmoonbirdfly** [comment]
我的插件最近也出现了和这个一模一样的情况。不仅加载不出答案，而且还会出现黑色的叉叉。课程对应网站是https://www.icourse163.org/course/NJU-1449589161和https://www.icourse163.org/course/NJU-1001571006

**Comment by ginnnnnncc** [comment]
先用网站吧

**Comment by moonmoonbirdfly** [comment]
> 先用网站吧

网站也没有那个mooc的答案诶😭

**Comment by moonmoonbirdfly** [comment]
> 先用网站吧
网站是指这个吗？
https://ginnnnnn.top/mooc/

如果是这个的话其实也搜不到我想查找的mooc😭

**Comment by ginnnnnncc** [comment]
> > 先用网站吧
> > 网站是指这个吗？
> > https://ginnnnnn.top/mooc/
> 
> 如果是这个的话其实也搜不到我想查找的mooc😭

先在网站左下角的加号那添加课程，插件的添加课程有些问题

**Comment by moonmoonbirdfly** [comment]
> > > 先用网站吧
> > > 网站是指这个吗？
> > > https://ginnnnnn.top/mooc/
> > 
> > 如果是这个的话其实也搜不到我想查找的mooc😭
> 
> 先在网站左下角的加号那添加课程，插件的添加课程有些问题，然后插件就能正常用了





谢谢博主，已经解决问题啦

**Comment by bargehaulersonvolga** [comment]
> 哪个课程，给下课程ID

https://www.icourse163.org/course/SEU-1468560167

**Comment by ginnnnnncc** [comment]
> > 哪个课程，给下课程ID
> 
> https://www.icourse163.org/course/SEU-1468560167

这个现在没问题了。对于此类情况，都可先去网站检查课程是否已被加入，点击左下角加号添加课程，再使用插件即可。后面插件会更新（最晚可能下学期开学前……）。

**Comment by ElysianGlow** [comment]
![image](https://github.com/ginnnnnncc/GinsMooc/assets/171119188/d9824fb0-fb75-4030-a55e-dec711694760)
<img width="623" alt="微信图片_20240529140043" src="https://github.com/ginnnnnncc/GinsMooc/assets/171119188/7af18e59-ef41-4955-aa88-f7712e63dcb2">
添加课程的时候进度显示-1%是怎么回事

**Comment by ElysianGlow** [comment]
<img width="623" alt="微信图片_20240529140043" src="https://github.com/ginnnnnncc/GinsMooc/assets/171119188/f9ba71a5-cb5b-4c12-a11a-44aa01a798aa">
添加课程的时候进度显示-1%该怎么解决

**Comment by ginnnnnncc** [comment]
> <img alt="微信图片_20240529140043" width="623" src="https://private-user-images.githubusercontent.com/171119188/334675213-f9ba71a5-cb5b-4c12-a11a-44aa01a798aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NjI4NzcsIm5iZiI6MTcxNjk2MjU3NywicGF0aCI6Ii8xNzExMTkxODgvMzM0Njc1MjEzLWY5YmE3MWE1LWNiNWItNGMxMi1hMTFhLTQ0YWEwMWE3OThhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOVQwNjAyNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODMyNzlkZTgwOGQyODBkNjUwYTg0Y2VjN2E2YTlmNmRjM2IwYzAzMmFmMzI3YjY1ZDA2NjY5NzhiOGE2MDJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R3XSMfb9OhM0-BazJynZHh8t1wJX3vPaxV143pSK9jI"> 添加课程的时候进度显示-1%该怎么解决

这个课程是不是SPOC，试了下加入不了课程

**Comment by ginnnnnncc** [comment]
> 对的，spoc是不行的嘛

对的，SPOC没有权限，获取不到数据

**Comment by ElysianGlow** [comment]
好滴，谢谢

**Comment by EdmunddXyx** [comment]
![QQ截图20240606205741](https://github.com/ginnnnnncc/GinsMooc/assets/171942053/f2a1c65f-72a2-491c-a519-3cbbb710fc07)
没有显示选项和答案
