### ISSUE TITLE
没有选项和答案

### ISSUE THREAD

**Issue by EdmunddXyx** [ginnnnnncc/GinsMooc#16]
![QQ截图20240606205741](https://github.com/ginnnnnncc/GinsMooc/assets/171942053/0d3c493e-2b21-43c0-9c90-9a48b07c464c)不显示选项和答案

**Comment by ginnnnnncc** [comment]
哪个课程

**Comment by EdmunddXyx** [comment]
浙江理工大学的‘中国近现代史纲要’

**Comment by EdmunddXyx** [comment]
> 哪个课程

浙江理工大学的‘中国近现代史纲要’ id:1472333502

**Comment by ginnnnnncc** [comment]
已修复

**Comment by ginnnnnncc** [comment]
不知道为什么有一部分获取不到，插件我试过了，能正常用，先用插件吧

**Comment by EdmunddXyx** [comment]
> 不知道为什么有一部分获取不到，插件我试过了，能正常用，先用插件吧

好的，谢谢
