### ISSUE TITLE
可否增加SPOC学校专有课程的答案获取功能？

### ISSUE THREAD

**Issue by HamburgBoy** [ginnnnnncc/GinsMooc#23]
您好！非常感谢您开发的这个插件~
由于部分课程开设了spoc学校专有课程，在使用过程中我发现插件无法获取到spoc课程的测试答案，可否添加这个功能呢？谢谢！！！

**Comment by ginnnnnncc** [comment]
一个用户只能认证一个学校，没有办法访问其它学校的spoc课程。如果要支持用户自己的账号访问，对用户来说有一定的技术门槛

**Comment by HamburgBoy** [comment]
> 一个用户只能认证一个学校，没有办法访问其它学校的spoc课程。如果要支持用户自己的账号访问，对用户来说有一定的技术门槛

好的好的，谢谢！
