### ISSUE TITLE
显示undifined,点击获取答案等待时间太久

### ISSUE THREAD

**Issue by cloudinfly** [ginnnnnncc/GinsMooc#25]
![image](https://github.com/user-attachments/assets/1146623f-ea8a-4098-8a05-0a0cedd17385)

**Comment by ginnnnnncc** [comment]
再试试

**Comment by cloudinfly** [comment]
在在线平台更新了网课地址就可以了，
![image](https://github.com/user-attachments/assets/36403c42-9eac-43ad-b99b-fdf4c6c9c1f9)
插件直接进入测验界面似乎一直没有显示更新课程内容？

**Comment by ginnnnnncc** [comment]
maybe是因为刚刚后端挂掉了，我重启了
