### ISSUE TITLE
课程清除前提醒

### ISSUE THREAD

**Issue by fans1106** [ginnnnnncc/GinsMooc#26]
建议增加课程清除前提醒功能，并保留结束课程答案1周左右

**Comment by ginnnnnncc** [comment]
当前实现是保留一个月

**Comment by ginnnnnncc** [comment]
而且如果需要的话可以自行重新添加

**Comment by ginnnnnncc** [comment]
> 当前实现是保留一个月

记错了，我改成一个月吧

**Comment by fans1106** [comment]
> 当前实现是保留一个月

嘶，那我猜测可能是课程问题，当课程被设置成“老师已关闭该学期，无法查看”状态时，答案数据就没了（课程结束时间是12月23日）
