### ISSUE TITLE
部分mooc被删除了，且不会自动更新即便显示为就绪

### ISSUE THREAD

**Issue by xiaoyuanxiao114514** [ginnnnnncc/GinsMooc#29]
![Image_1306403776612635](https://github.com/user-attachments/assets/5113144f-19a8-44cb-a143-26051393354f)
![Image_1306405348591281](https://github.com/user-attachments/assets/d5d9d78b-2b56-4bcd-8811-5a7a69a02bd7)
![Image_1306406789283468](https://github.com/user-attachments/assets/c13ead83-b307-4f49-82cf-63721f1e6374)
![Image_1306408597187114](https://github.com/user-attachments/assets/80d51406-c8cf-4052-8cfd-83a673c90715)

**Comment by ginnnnnncc** [comment]
现在再看看

**Comment by xiaoyuanxiao114514** [comment]
现在可以了，多谢
