### ISSUE TITLE
大佬你好,请问用谷歌加载下载的文件夹显示"未能成功加载扩展程序"怎么办

### ISSUE THREAD

**Issue by nihaodaming** [ginnnnnncc/GinsMooc#9]
![(XGV8_F_WLYOAL9(J @~4@R](https://github.com/ginnnnnncc/GinsMooc/assets/122172408/f6efdf9b-5646-453b-aced-d2326fd7349e)

**Comment by ginnnnnncc** [comment]
你加载一整个仓库了，你从release里面下，刚刚发了最新的，或者从[官网](https://ginnnnnn.top/mooc/)下
